function generateExcelBlob(headers, rows, title) {
  const escapeHtml = (s) => (s || '').toString().replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

  let html = `<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">`;
  html += `<head><meta charset="UTF-8"><!--[if gte mso 9]><xml><x:ExcelWorkbook><x:ExcelWorksheets><x:ExcelWorksheet><x:Name>Report</x:Name><x:WorksheetOptions><x:DisplayGridlines/></x:WorksheetOptions></x:ExcelWorksheet></x:ExcelWorksheets></x:ExcelWorkbook></xml><![endif]--></head>`;
  html += `<body><table>`;

  if (title) {
    html += `<tr><td colspan="${headers.length}" style="font-size:16px;font-weight:bold;padding:8px;">${escapeHtml(title)}</td></tr>`;
  }

  html += `<tr>`;
  for (const h of headers) {
    html += `<th style="background:#4472C4;color:#fff;padding:6px 10px;border:1px solid #ccc;font-weight:bold;">${escapeHtml(h)}</th>`;
  }
  html += `</tr>`;

  for (const row of rows) {
    html += `<tr>`;
    for (const h of headers) {
      const val = row[h] !== undefined ? row[h] : '';
      html += `<td style="padding:4px 10px;border:1px solid #ccc;${val === '' ? 'background:#fff3f3;' : ''}">${escapeHtml(val)}</td>`;
    }
    html += `</tr>`;
  }

  html += `</table></body></html>`;

  return new Blob([html], { type: 'application/vnd.ms-excel;charset=utf-8' });
}

function generatePdfHtml(title, subtitle, headers, rows, filters) {
  const escapeHtml = (s) => (s || '').toString().replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

  let html = `<!DOCTYPE html><html><head><meta charset="UTF-8"><title>${escapeHtml(title)}</title>`;
  html += `<style>
    @page { size: landscape; margin: 15mm; }
    body { font-family: Calibri, Arial, sans-serif; font-size: 10px; }
    h1 { font-size: 16px; margin: 0 0 4px; }
    .subtitle { font-size: 12px; color: #555; margin-bottom: 12px; }
    table { width: 100%; border-collapse: collapse; font-size: 9px; }
    th { background: #4472C4; color: #fff; padding: 4px 6px; border: 1px solid #999; text-align: center; font-weight: bold; }
    td { padding: 3px 6px; border: 1px solid #ccc; }
    td.empty { background: #fff3f3; }
    tr:nth-child(even) { background: #f5f5f5; }
    .footer { margin-top: 8px; font-size: 9px; color: #888; }
  </style></head><body>`;

  html += `<h1>${escapeHtml(title)}</h1>`;
  if (subtitle) html += `<div class="subtitle">${escapeHtml(subtitle)}</div>`;
  if (filters && filters.length > 0) {
    html += `<div class="subtitle">Filters: ${escapeHtml(filters.map(f => `${f.field} ${f.operator} ${f.value || ''}`).join(' | '))}</div>`;
  }

  html += `<table><thead><tr>`;
  for (const h of headers) {
    html += `<th>${escapeHtml(h)}</th>`;
  }
  html += `</tr></thead><tbody>`;

  for (const row of rows) {
    html += `<tr>`;
    for (const h of headers) {
      const val = row[h] !== undefined ? row[h] : '';
      html += `<td class="${val === '' ? 'empty' : ''}">${escapeHtml(val)}</td>`;
    }
    html += `</tr>`;
  }

  html += `</tbody></table>`;
  html += `<div class="footer">Generated by CNF Report Analyzer | ${new Date().toLocaleString()} | ${rows.length} records</div>`;
  html += `</body></html>`;

  return html;
}

function openPdfWindow(title, subtitle, headers, rows, filters) {
  const html = generatePdfHtml(title, subtitle, headers, rows, filters);
  const w = window.open('', '_blank');
  w.document.write(html);
  w.document.close();
  setTimeout(() => { w.print(); }, 500);
}

function downloadExcel(title, headers, rows) {
  const blob = generateExcelBlob(headers, rows, title);
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${title.replace(/[^a-z0-9]/gi, '_')}.xls`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
